services:
    ntopng:
        container_name: ntopng
        network_mode: host
        privileged: true
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - /etc/ntopng.license:/etc/ntopng.license:ro
            - ./ntopng-data:/var/lib/ntopng
        depends_on:
            - clickhouse
        command: [
            '--interface=eth0',
            '--local-networks=192.168.1.0/24',
            '--http-port=3000',
            '--data-dir=/var/lib/ntopng',
            '--community'
        ]
        image: ntop/ntopng:latest
        restart: unless-stopped
    netflow2ng:
        container_name: netflow2ng
        ports:
            - 2056:2055/udp
        entrypoint: ["/netflow2ng", "--log-level=debug", "--tlv"]
        image: synfinatic/netflow2ng
        restart: unless-stopped
        networks:
            ntop:
                ipv4_address: 10.0.1.3

    clickhouse:
        image: clickhouse/clickhouse-server:latest
        hostname: clickhouse
        container_name: clickhouse
        restart: unless-stopped
        environment:
            - CLICKHOUSE_USER=ntopng
            - CLICKHOUSE_PASSWORD=ntopng
            - CLICKHOUSE_DB=ntopng
        volumes:
            - ./db/data:/var/lib/clickhouse
            - ./db/logs:/var/log/clickhouse-server
        networks:
            ntop:
                ipv4_address: 10.0.1.4

    redis:
        container_name: ntopng-redis
        volumes:
            - ./redis:/data
        image: redis:6.2-alpine
        command: redis-server --appendonly yes --requirepass redispassword
        restart: always
        networks:
            ntop:
                ipv4_address: 10.0.1.5

networks:
    ntop:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.1.0/28
