---
# JIRA System Maintenance Playbook
# Target: PCT-102 (192.168.1.22) - JIRA Container
# Purpose: Comprehensive system maintenance including OS updates, log cleanup, and JIRA health checks
# Schedule: Weekly maintenance, monthly comprehensive

- name: JIRA System Maintenance
  hosts: jira-server
  become: yes

  vars:
    maintenance_log: "/var/log/ansible-jira-maintenance.log"
    log_retention_days: 30
    jira_home: "/var/atlassian/application-data/jira"
    jira_logs: "{{ jira_home }}/log"
    catalina_logs: "/opt/atlassian/jira/logs"
    tomcat_logs: "/opt/atlassian/jira/tomcat/logs"

  tasks:
    # ========================================
    # MAINTENANCE INITIALIZATION
    # ========================================

    - name: Create maintenance log entry
      lineinfile:
        path: "{{ maintenance_log }}"
        line: "=== JIRA system maintenance started: {{ ansible_date_time.iso8601 }} ==="
        create: yes
      tags: always

    - name: Check disk usage before maintenance
      shell: df -h / | tail -1
      register: disk_usage_before
      changed_when: false
      tags: always

    # ========================================
    # SYSTEM LOG CLEANUP
    # ========================================

    - name: Rotate and clean system journals
      shell: journalctl --vacuum-time={{ log_retention_days }}d
      register: journal_cleanup
      tags: logs

    - name: Clean old syslog files
      find:
        paths: /var/log
        patterns: "*.log.*,*.gz,syslog.*,daemon.log.*"
        age: "{{ log_retention_days }}d"
      register: old_syslogs
      tags: logs

    - name: Remove old syslog files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ old_syslogs.files }}"
      when: old_syslogs.matched > 0
      tags: logs

    # ========================================
    # JIRA LOG CLEANUP
    # ========================================

    - name: Find old JIRA application logs
      find:
        paths: "{{ jira_logs }}"
        patterns: "atlassian-jira*.log.*,catalina*.log.*,*.gz"
        age: "{{ log_retention_days }}d"
      register: old_jira_logs
      ignore_errors: yes
      tags: logs

    - name: Remove old JIRA application logs
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ old_jira_logs.files }}"
      when: old_jira_logs.matched > 0
      tags: logs

    - name: Truncate large JIRA logs (>500MB)
      shell: |
        find {{ jira_logs }} -name "atlassian-jira*.log" -type f -size +500M -exec truncate -s 200M {} \; 2>/dev/null || true
      tags: logs

    - name: Find old Catalina logs
      find:
        paths: "{{ catalina_logs }}"
        patterns: "catalina*.log.*,localhost*.log.*,*.gz"
        age: "{{ log_retention_days }}d"
      register: old_catalina_logs
      ignore_errors: yes
      tags: logs

    - name: Remove old Catalina logs
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ old_catalina_logs.files }}"
      when: old_catalina_logs.matched > 0
      tags: logs

    - name: Find old Tomcat access logs
      find:
        paths: "{{ tomcat_logs }}"
        patterns: "localhost_access_log*.txt,catalina.out.*"
        age: "{{ log_retention_days }}d"
      register: old_tomcat_logs
      ignore_errors: yes
      tags: logs

    - name: Remove old Tomcat logs
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ old_tomcat_logs.files }}"
      when: old_tomcat_logs.matched > 0
      tags: logs

    - name: Truncate catalina.out if too large (>1GB)
      shell: |
        if [ -f {{ catalina_logs }}/catalina.out ]; then
          size=$(stat -f%z {{ catalina_logs }}/catalina.out 2>/dev/null || stat -c%s {{ catalina_logs }}/catalina.out)
          if [ $size -gt 1073741824 ]; then
            tail -c 200M {{ catalina_logs }}/catalina.out > {{ catalina_logs }}/catalina.out.tmp
            mv {{ catalina_logs }}/catalina.out.tmp {{ catalina_logs }}/catalina.out
            echo "Truncated catalina.out from $(($size / 1048576))MB to 200MB"
          fi
        fi
      register: catalina_truncate
      changed_when: "'Truncated' in catalina_truncate.stdout"
      tags: logs

    # ========================================
    # JIRA WORK DIRECTORY CLEANUP
    # ========================================

    - name: Find old JIRA import/export files
      find:
        paths: "{{ jira_home }}/import,{{ jira_home }}/export"
        patterns: "*"
        age: "60d"
      register: old_import_exports
      ignore_errors: yes
      tags: logs

    - name: Remove old JIRA import/export files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ old_import_exports.files }}"
      when: old_import_exports.matched > 0
      tags: logs

    - name: Clean JIRA temp directory
      shell: |
        find {{ jira_home }}/tmp -type f -mtime +7 -delete 2>/dev/null || true
        find {{ jira_home }}/tmp -type d -empty -delete 2>/dev/null || true
      ignore_errors: yes
      tags: logs

    # ========================================
    # SYSTEM PACKAGE UPDATES
    # ========================================

    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: updates

    - name: Upgrade all packages (dist-upgrade)
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      register: apt_updates
      tags: updates

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      tags: updates

    # ========================================
    # JIRA SERVICE HEALTH CHECKS
    # ========================================

    - name: Check JIRA process status
      shell: ps aux | grep -i "[j]ira" | wc -l
      register: jira_process_count
      changed_when: false
      tags: health

    - name: Check JIRA HTTP port
      shell: |
        netstat -tlnp | grep ':8080' || ss -tlnp | grep ':8080'
      register: jira_port
      changed_when: false
      ignore_errors: yes
      tags: health

    - name: Check JIRA database connectivity
      shell: |
        ps aux | grep -i "[p]ostgres" | wc -l
      register: db_process_count
      changed_when: false
      tags: health

    - name: Get JIRA application status via systemd
      systemd:
        name: jira
        state: started
      check_mode: yes
      register: jira_service_status
      ignore_errors: yes
      tags: health

    # ========================================
    # DATABASE MAINTENANCE (POSTGRESQL)
    # ========================================

    - name: Check PostgreSQL service
      systemd:
        name: postgresql
        state: started
        enabled: yes
      ignore_errors: yes
      tags: database

    - name: Vacuum JIRA database (comprehensive mode only)
      shell: |
        su - postgres -c "vacuumdb --analyze jira" 2>&1 || true
      when: comprehensive_maintenance is defined and comprehensive_maintenance | bool
      register: db_vacuum
      ignore_errors: yes
      tags: comprehensive

    # ========================================
    # POST-MAINTENANCE ASSESSMENT
    # ========================================

    - name: Check disk usage after maintenance
      shell: df -h / | tail -1
      register: disk_usage_after
      changed_when: false
      tags: always

    - name: Calculate space freed
      shell: |
        before=$(df / | tail -1 | awk '{print $3}')
        after=$(df / | tail -1 | awk '{print $3}')
        freed=$((before - after))
        if [ $freed -lt 0 ]; then freed=0; fi
        echo "${freed}K"
      register: space_freed
      changed_when: false
      tags: always

    # ========================================
    # COMPREHENSIVE MAINTENANCE (MONTHLY)
    # ========================================

    - name: Clean APT cache thoroughly (comprehensive mode only)
      shell: |
        apt-get clean
        apt-get autoclean
        rm -rf /var/cache/apt/archives/*.deb
      when: comprehensive_maintenance is defined and comprehensive_maintenance | bool
      tags: comprehensive

    - name: Reindex JIRA search (comprehensive mode only)
      shell: |
        # This would typically be done via JIRA REST API
        echo "Manual reindex recommended via JIRA admin UI"
      when: comprehensive_maintenance is defined and comprehensive_maintenance | bool
      tags: comprehensive

    # ========================================
    # MAINTENANCE REPORTING
    # ========================================

    - name: Log maintenance results
      blockinfile:
        path: "{{ maintenance_log }}"
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK {{ ansible_date_time.iso8601 }} -->"
        block: |
          Maintenance Summary:
          - Date: {{ ansible_date_time.iso8601 }}
          - Disk Usage Before: {{ disk_usage_before.stdout }}
          - Disk Usage After: {{ disk_usage_after.stdout }}
          - Space Freed: {{ space_freed.stdout }}
          - System Updates: {{ apt_updates.changed | default(false) }}
          - Journal Cleaned: {{ journal_cleanup.changed | default(false) }}
          - JIRA Logs Removed: {{ old_jira_logs.matched | default(0) }} files
          - Catalina Logs Removed: {{ old_catalina_logs.matched | default(0) }} files
          - Tomcat Logs Removed: {{ old_tomcat_logs.matched | default(0) }} files
          - JIRA Processes: {{ jira_process_count.stdout }}
          - JIRA Port Status: {{ 'Listening' if jira_port.rc == 0 else 'Not listening' }}
          - Reboot Required: {{ 'YES' if reboot_required.stat.exists else 'NO' }}
          {% if comprehensive_maintenance is defined and comprehensive_maintenance | bool %}
          - Database Vacuum: {{ 'Completed' if db_vacuum.rc == 0 else 'Failed' }}
          {% endif %}
      tags: always

    - name: Send maintenance summary
      debug:
        msg: |
          ============================================
          JIRA System Maintenance Summary
          ============================================
          Host: {{ ansible_hostname }}
          Date: {{ ansible_date_time.iso8601 }}

          DISK USAGE:
          Before: {{ disk_usage_before.stdout }}
          After:  {{ disk_usage_after.stdout }}
          Space Freed: {{ space_freed.stdout }}

          SYSTEM UPDATES:
          Updates Applied: {{ apt_updates.changed | default(false) }}
          Reboot Required: {{ 'YES - MANUAL REBOOT NEEDED' if reboot_required.stat.exists else 'NO' }}

          LOG CLEANUP:
          System Journals: {{ journal_cleanup.changed | default(false) }}
          JIRA Logs: {{ old_jira_logs.matched | default(0) }} files removed
          Catalina Logs: {{ old_catalina_logs.matched | default(0) }} files removed
          Tomcat Logs: {{ old_tomcat_logs.matched | default(0) }} files removed
          Catalina.out: {{ catalina_truncate.stdout | default('Not truncated') }}
          Import/Export: {{ old_import_exports.matched | default(0) }} files removed

          JIRA STATUS:
          JIRA Processes: {{ jira_process_count.stdout }}
          HTTP Port (8080): {{ 'Listening' if jira_port.rc == 0 else 'NOT LISTENING - CHECK SERVICE' }}
          Database Processes: {{ db_process_count.stdout }}

          {% if comprehensive_maintenance is defined and comprehensive_maintenance | bool %}
          COMPREHENSIVE MAINTENANCE:
          Database Vacuum: {{ 'Completed' if db_vacuum.rc == 0 else 'Failed/Skipped' }}
          APT Cache: Cleaned
          {% endif %}

          ============================================
      tags: always

    - name: Create maintenance completion marker
      lineinfile:
        path: "{{ maintenance_log }}"
        line: "=== JIRA maintenance completed successfully: {{ ansible_date_time.iso8601 }} ==="
      tags: always
